### ISSUE TITLE
DataGrid: Alternating rows

### ISSUE THREAD

**Issue by rsuter** [MyToolkit/MyToolkit#1]
Add a way to add alternating row coloring in the [DataGrid](https://github.com/MyToolkit/MyToolkit/wiki/DataGrid)

**Comment by Trolldemorted** [comment]
@rsuter could you please tell me how i can disable this feature? For ordinary tables it makes perfect sense, but i really would like to have uniform colored rows in my app.

And how can i disable the highlighing of the selected row?

I tried both with `DataGrid.RowStyle`, but so far everything i tried either disabled all highlighting (i would like to keep the pointed-over hover effect) or crashed the app.
