### ISSUE TITLE
"Invalid URI: The format of the URI could not be determined." on universal app.

### ISSUE THREAD

**Issue by Englbach** [MyToolkit/MyToolkit#10]
var youtube = await YouTube.GetVideoUriAsync("e-ORhEE9VVg", YouTubeQuality.Quality720P);
                            if (youtube != null)
                            {
                                Uri t = youtube.Uri;
                            }

....
catch (Exception ex)
            {
                var dialog = new MessageDialog(ex.Message);
                await dialog.ShowAsync();
            }

"var youtube" has return a ""Invalid URI: The format of the URI could not be determined.".
- References:
Microsoft.Bcl.Async
Mytoolkit
Mytoolkit.Extended.

**Comment by rsuter** [comment]
Is this a UWP (Win10) app?

**Comment by rsuter** [comment]
A new NuGet package version which solves the problem will be released today or tomorrow...

**Comment by Englbach** [comment]
yes. It is UWP.

**Comment by Englbach** [comment]
I must remove this references.

**Comment by rsuter** [comment]
Which references?

**Comment by Englbach** [comment]
Microsoft.Bcl.Async Mytoolkit Mytoolkit.Extended

**Comment by rsuter** [comment]
Why?

**Comment by Englbach** [comment]
A new NuGet package version which solves the problem will be released today or tomorrow... If new NuGet be upgraded that I should installed again.

**Comment by rsuter** [comment]
You can also update an existing package in your project...

**Comment by Englbach** [comment]
Are you sure "A new NuGet package version which solves the problem will be released today or tomorrow".

**Comment by rsuter** [comment]
Ok, the new package is now available, please update to 2.4.0 and try again

**Comment by Englbach** [comment]
I don't see it. Mytoolkip still is 2.3.31 version.
A new Nuget is 2.8.6

**Comment by rsuter** [comment]
Its live: https://www.nuget.org/packages/MyToolkit/

**Comment by rsuter** [comment]
https://www.nuget.org/packages/MyToolkit.Extended/

**Comment by rsuter** [comment]
Maybe it was not indexed before...

**Comment by Englbach** [comment]
It's not OK.

**Comment by Englbach** [comment]
![1](https://cloud.githubusercontent.com/assets/11801842/9007159/ca5e9966-37b8-11e5-98ce-ce284c40afef.png)

**Comment by Englbach** [comment]
I debug x86.

**Comment by rsuter** [comment]
try to uninstall and reinstall the package.. What is not working?

**Comment by Englbach** [comment]
I have uninstall and reinstall but it is not ok.
var youtube = await YouTube.GetVideoUriAsync("e-ORhEE9VVg", YouTubeQuality.Quality720P);
Invalid URI: The format of the URI could not be determined

**Comment by rsuter** [comment]
Just tried, it works for me... are you sure you have the newest version installed?

**Comment by Englbach** [comment]
yes.

**Comment by Englbach** [comment]
I'm trying it again.

**Comment by Englbach** [comment]
PM> Install-Package MyToolkit.Extended 
Successfully installed 'MyToolkit.Extended 2.3.31' to NewProject
Why?

**Comment by rsuter** [comment]
Try `Install-Package MyToolkit -Version 2.4.0`

**Comment by Englbach** [comment]
private async void t()
        {
            try
            {
                var you = await YouTube.GetVideoUriAsync("HMVYT3QvDW8", YouTubeQuality.Quality360P);
                if(you!=null)
                {
                    string s = "s";
                }
            }
            catch(Exception ex)
            {
                
            }
        }
It is not ok. I don't understand

**Comment by rsuter** [comment]
Open your project.json and check if MyToolkit.Extended is installed in v2.4

**Comment by Englbach** [comment]
Ok. I have successfully. Thanks you.

**Comment by rsuter** [comment]
So, is it working now?

**Comment by Englbach** [comment]
yes. It is.

**Comment by rsuter** [comment]
Ok, nice. Please star the project if you like the library... Have a nice day.
