### ISSUE TITLE
MtObservableCollection.AddRange throws an exception

### ISSUE THREAD

**Issue by Bert-Proesmans** [MyToolkit/MyToolkit#102]
Hi!
I'm trying to make use of the additional functionality of the MtObservableCollection class. I'm currently running VS2019 and am building a WPF application on .Net 4.7.2.

The method MtObservableCollection.AddRange() throws an NotSupportedException.  
Source: PresentationFramework  
Message: Range operations are not supported (this is a translation from Dutch to English)  
with the following stacktrace;
<details>

```text
   bij System.Windows.Data.ListCollectionView.ValidateCollectionChangedEventArgs(NotifyCollectionChangedEventArgs e)
   bij System.Windows.Data.ListCollectionView.ProcessCollectionChanged(NotifyCollectionChangedEventArgs args)
   bij System.Windows.Data.CollectionView.OnCollectionChanged(Object sender, NotifyCollectionChangedEventArgs args)
   bij System.Collections.ObjectModel.ObservableCollection`1.OnCollectionChanged(NotifyCollectionChangedEventArgs e)
   bij MyToolkit.Collections.MtObservableCollection`1.OnCollectionChanged(NotifyCollectionChangedEventArgs e)
   bij MyToolkit.Collections.MtObservableCollection`1.AddRange(IEnumerable`1 collection)
   bij HSPacketAnalyzer.ViewModels.PacketInspectorViewModel.SetSamplePackets() in E:\Git\hearthsim-group\HSPacketAnalyzer\HSPacketAnalyzer\ViewModels\PacketInspectorViewModel.cs:regel 67
   bij HSPacketAnalyzer.ViewModels.PacketInspectorViewModel.OnLoaded() in E:\Git\hearthsim-group\HSPacketAnalyzer\HSPacketAnalyzer\ViewModels\PacketInspectorViewModel.cs:regel 37
   bij MyToolkit.Mvvm.ViewModelBase.CallOnLoaded()
   bij HSPacketAnalyzer.Views.PacketInspectorWindow.<.ctor>b__2_0(Object <p0>, RoutedEventArgs <p1>) in E:\Git\hearthsim-group\HSPacketAnalyzer\HSPacketAnalyzer\Views\PacketInspectorWindow.xaml.cs:regel 30
   bij System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   bij System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   bij System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   bij System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
   bij System.Windows.BroadcastEventHelper.BroadcastEvent(DependencyObject root, RoutedEvent routedEvent)
   bij System.Windows.BroadcastEventHelper.BroadcastLoadedEvent(Object root)
   bij MS.Internal.LoadedOrUnloadedOperation.DoWork()
   bij System.Windows.Media.MediaContext.FireLoadedPendingCallbacks()
   bij System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   bij System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   bij System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   bij System.Windows.Media.MediaContext.Resize(ICompositionTarget resizedCompositionTarget)
   bij System.Windows.Interop.HwndTarget.OnResize()
   bij System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)
   bij System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   bij MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   bij MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   bij System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   bij System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

</details>

I understand that i cannot use the AddRange method, but i'm unsure if the exception is thrown because of the container or any connected control/type.
Am i supposed to use a specialized control to make full use of the MtObservableCollection type?
Is this feature just not available on the .Net Framework platform?
Is there something else going on? Mind that i'm not deeply experienced with WPF (or .Net in general)

Thanks for taking the time to read this issue.
Bert

**Comment by RicoSuter** [comment]
Are you sure its the MtObservableCollection class who throws this or is it another one which is called because the items changed?

**Comment by Bert-Proesmans** [comment]
That's what I'm not sure about. It only throws an exception when the MtObservableCollection is directly used as ItemsSource for System.Windows.Controls.DataGrid in my view. 
Calling AddRange without having the DataGrid bound does not show any exceptions.

My project is simple at the moment; App -> loads view -> loads ViewModel -> initializes data.

I went with (for me) intuitive usage; MtObservableCollection is a drop-in replacement for ObservableCollection. This exception shows that's not the case.
Do I need to use a special DataGrid control? Is the DataGrid 'just not compatible' with any collection range operations?

**Comment by RicoSuter** [comment]
Its strange mtobscoll actually does not call addrange:

https://github.com/RSuter/MyToolkit/blob/master/src/MyToolkit/Collections/MtObservableCollection.cs

**Comment by RicoSuter** [comment]
Maybe you need to clone the sln and debug this in the sample app

**Comment by Bert-Proesmans** [comment]
1. Downloaded the solution
2. Added a ViewModel to SampleWpfApplication
3. Added MtObservableCollection to MainWindow class
4. Added DataGrid to MainWindow XAML
5. Hooked up codebehind as datacontext and bound DataGrid ItemsSource to MtObservableCollection
6. Created new method that's called at initialize to insert 2 viewmodel instances with AddRange
7. Updated MainWindow constructor to use the Loaded event to call Initialize
8. Ran application

The exception is reported to the following line, but it actually happened deeper down the callstack, It wasn't possible to reach the exact point of exception through VS debugger. 
https://github.com/RSuter/MyToolkit/blob/3959db18fe615e5ded82d148393e06395d0b8955/src/MyToolkit/Collections/MtObservableCollection.cs#L127

This method has been called by line 61 in the same file. Line 61 is part of the AddRange method directly.

<details>
<summary>
NotSupportedException - Operations on ranges are not supported.  
Full Stack trace
</summary>

```text
   bij System.Windows.Data.ListCollectionView.ValidateCollectionChangedEventArgs(NotifyCollectionChangedEventArgs e)
   bij System.Windows.Data.ListCollectionView.ProcessCollectionChanged(NotifyCollectionChangedEventArgs args)
   bij System.Windows.Data.CollectionView.OnCollectionChanged(Object sender, NotifyCollectionChangedEventArgs args)
   bij System.Collections.ObjectModel.ObservableCollection`1.OnCollectionChanged(NotifyCollectionChangedEventArgs e)
   bij MyToolkit.Collections.MtObservableCollection`1.OnCollectionChanged(NotifyCollectionChangedEventArgs e) in C:\Users\Bert\Downloads\MyToolkit-604c36cd5ca6b2846a880d3e78c9e3881df931cd\MyToolkit-604c36cd5ca6b2846a880d3e78c9e3881df931cd\src\MyToolkit\Collections\MtObservableCollection.cs:regel 127
   bij MyToolkit.Collections.MtObservableCollection`1.AddRange(IEnumerable`1 collection) in C:\Users\Bert\Downloads\MyToolkit-604c36cd5ca6b2846a880d3e78c9e3881df931cd\MyToolkit-604c36cd5ca6b2846a880d3e78c9e3881df931cd\src\MyToolkit\Collections\MtObservableCollection.cs:regel 61
   bij SampleWpfApplication.MainWindow.InsertViewModelItems() in C:\Users\Bert\Downloads\MyToolkit-604c36cd5ca6b2846a880d3e78c9e3881df931cd\MyToolkit-604c36cd5ca6b2846a880d3e78c9e3881df931cd\src\SampleWpfApplication\MainWindow.xaml.cs:regel 103
   bij SampleWpfApplication.MainWindow.<Initialize>d__5.MoveNext() in C:\Users\Bert\Downloads\MyToolkit-604c36cd5ca6b2846a880d3e78c9e3881df931cd\MyToolkit-604c36cd5ca6b2846a880d3e78c9e3881df931cd\src\SampleWpfApplication\MainWindow.xaml.cs:regel 75
```

</details>

**Comment by Bert-Proesmans** [comment]
So the problem lies with the windows Datagrid control. I'll need to find an extension on this control that can handle range operations then.
