### ISSUE TITLE
Could Mytoolkit get information about "likes_count" "deslike_count" on youtube?

### ISSUE THREAD

**Issue by Englbach** [MyToolkit/MyToolkit#11]
I want to get more information from id_ youtube. Could Mytoolkit get information about "likes_count" "deslike_count" on youtube?

**Comment by rsuter** [comment]
Isnt there an official yt sdk to do that?

**Comment by Englbach** [comment]
I don't know how do they get those information.

**Comment by rsuter** [comment]
Have a look at https://developers.google.com/youtube/v3/?hl=en
