### ISSUE TITLE
Invalid URI

### ISSUE THREAD

**Issue by shreedhar-ww** [MyToolkit/MyToolkit#12]
I am getting error message (Invalid URI: The format of the URI could not be determined.) when i tried to access the youtube URL "https://www.youtube.com/watch?v=7M_jHUawccI".
Can you please check  this issue.
try
{

 var url = await YouTube.GetVideoUriAsync("7M_jHUawccI", YouTubeQuality.Quality720P);
 player.Source = url.Uri;
 player.Play();

}
catch
{
//
}

**Comment by rsuter** [comment]
I think this is a rtmpe stream and you cannot get the MP4 link... see https://de.wikipedia.org/wiki/Protected_Streaming, I could not find a way to play these videos...

**Comment by shreedhar-ww** [comment]
Thanks for updating me.
