### ISSUE TITLE
OnNavigatingFrom() and OnNavigatedFrom() are called on target page when navigating backwards in stack

### ISSUE THREAD

**Issue by danielthompson** [MyToolkit/MyToolkit#13]
Hi,

First off, we're on 2.3.21, so this may be an issue that's fixed in the latest build. We're in the middle of a very large project, so we tend to wait until we've hit a relative stability peak before upgrading libraries. 

In any event, we've found that the following is happening:

1. Navigate from Page1 to Page2
-> `Page1.OnNavigatingFrom()` and `Page1.OnNavigatedFrom()` are correctly called

2. Then, navigate backwards from Page2 to Page1 using `Frame.GoBackAsync()`
-> `Page1.OnNavigatingFrom()` and `Page1.OnNavigatedFrom()` are called. 

I think this behavior is incorrect: since we're navigating from Page2 to Page1,  `Page1.OnNavigatingFrom()` and `Page1.OnNavigatedFrom()` shouldn't be called. Thoughts?

**Comment by rsuter** [comment]
In the current version 2.4.1-beta (latest source code). Clone the latest source code and run the SampleUwpApp or SampleWindowsStoreApp in debug mode and check navigation events in the Visual Studio output. It works fine for me...

**Comment by danielthompson** [comment]
We upgraded to 2.4.0 and are still seeing the issue. Investigating further...

**Comment by danielthompson** [comment]
To give some context around this - our app is structured such that we allow random access navigation to the various views. When navigating, we first check to see if the requested target page is already on the stack. if so, we pop the intermediate pages and then navigate back to the target page. if not, we navigate forward to the target. 

code:

      public async void NavigateToView(IView currentView, Type newViewType, IViewContext context)
      {
         MtPageDescription pageDescription = currentView.Frame.GetNearestPageOfTypeInBackStack(newViewType);

         if (pageDescription != null)
         {
            if (currentView.Frame.CurrentPage != pageDescription)
            {
               // Remove pages from stack until reaching the desired one.
               // http://stackoverflow.com/questions/29127993/mtframe-gobacktoasync-pop-or-navigate-back-to-nth-page-without-loading-n-1-pages
               while (currentView.Frame.PreviousPage != pageDescription)
               {
                  currentView.Frame.RemovePageFromStackAt(currentView.Frame.CurrentIndex - 1);
               }
              
               if (currentView.Frame.CanGoBack)
                  // debugger stepthrough shows this is being called when nav requested from Page2 to Page1
                  await currentView.Frame.GoBackAsync()
            }
         }

         await currentView.Frame.NavigateAsync(newViewType, context);
      }

**Comment by rsuter** [comment]
Looks good without testing... However, have you tried to use GoBackToAsync?

**Comment by rsuter** [comment]
FYI: In the next version there will be a method to move a given page to the top of the stack without removing pages in between...

**Comment by danielthompson** [comment]
Interesting, we'll try `GoBackToAsync()` and see if we see the same behavior.

**Comment by danielthompson** [comment]
Turns out it was a bug in our nav method. After navigating back to the target view, we were still navigating forward to the target view.

     public async void NavigateToView(IView currentView, Type newViewType, IViewContext context)
     {
        MtPageDescription pageDescription = currentView.Frame.GetNearestPageOfTypeInBackStack(newViewType);

        if (pageDescription != null)
        {
           if (currentView.Frame.CurrentPage != pageDescription)
           {
              // nav backward - correct
           }
        }
        // nav forward - there should be an else wrapping the following statement
        await currentView.Frame.NavigateAsync(newViewType, context);
     }

**Comment by rsuter** [comment]
Ok, so this issue can be closed?

**Comment by danielthompson** [comment]
Yes sir. Thanks for your help. We did switch to GoBackToAsync() and it seems to be working as well, nice add.
