### ISSUE TITLE
DataGrid NullReferenceException 

### ISSUE THREAD

**Issue by Palmar87** [MyToolkit/MyToolkit#14]
Hi

I have been using an old version of MyToolKit, 2.3.17, and when I updated to the newest version one of my DataGrids has been causing a crash that wasn't present with the old version. 
After debugging a bit I found out that this line

    Items.Ascending = SelectedColumn.IsAscending;

in the UpdateOrder method in DataGrid.cs is causing the issue.
Looking at the DataGrid I noticed that all columns were of type DataGridTemplatedColumn and that seems to be the reason SelectedColumn is null.

Regards, Pálmar

**Comment by rsuter** [comment]
Do you think this fixed the bug?
https://github.com/MyToolkit/MyToolkit/commit/24f4a5513208a6cda6b2c1dda1fbdb20e60c3388

**Comment by Palmar87** [comment]
This would fix it and I don't see it causing any new problems. Let me know when I can update to a version with the new changes.

**Comment by rsuter** [comment]
Ill release a new nuget version on this weekend...

**Comment by rsuter** [comment]
Version 2.4.2 is now available as NuGet package...
