### ISSUE TITLE
Hamburger button issues on Windows Phone 10

### ISSUE THREAD

**Issue by tomreich** [MyToolkit/MyToolkit#18]
Hey folks, I'll start by saying MyToolkit is pretty sweet and thanks for your hard work.

I'm in the process of converting my UWP app's Hamburger buttons from a SplitView over to your HamburgerFrameBuilder.  Everything seems to be working great on Windows 10 desktop, but I run into some issues when I deploy on Windows Phone 10.  Namely, whenever I tap any of the PageHamburgerItems, I get an error:

>Error: Converter failed to convert value of type 'MyToolkit.Controls.PageHamburgerItem, MyToolkit.Extended, Version=2.4.2.0, Culture=neutral, PublicKeyToken=null' to type 'HamburgerItem'; BindingExpression: Path='SelectedTopItem' DataItem='MyToolkit.Controls.Hamburger'; target element is 'Windows.UI.Xaml.Controls.ListBox' (Name='null'); target property is 'SelectedItem' (type 'Object'). 

Here's the code I used to create the item in question:
```C#
    new PageHamburgerItem
    {
      Content = "Home",
      ContentIcon = new SymbolIcon(Symbol.Home),
      Icon = new SymbolIcon(Symbol.Home),
      PageType = typeof(MainPage)
    }
```
I get a similar error with the search box.

I added MTK to my solution using Nuget about two days back so I'm pretty sure I've got the latest version.

Any suggestions?  Happy to provide more details if necessary.

Update: I tried deploying your MtToolkit.VS2015 sample application to my phone; same results.  The device is a Lumia 920 and I'm running build 10581.

**Comment by rsuter** [comment]
I currently dont have a working phone running W10M. Is it also reproducable on the emulator?

**Comment by rsuter** [comment]
I deployed the sample UWP app to my emulator and did not see any problems. What exactly are you doing in the app? Or does the exception occur directly after launch without any interaction? (I have an old emulator build, now downloading/installing the latest emulators)

**Comment by tomreich** [comment]
I'm able to duplicate it with your MyToolkit.VS2015 project:

1.  Launch the app
2.  Tap any of the PageHamburgerItem icons on the Hamburger Menu

The tapped PageHamburgerItem becomes selected, but the page does not change, and the error I listed above appears in the VS Console.

I don't have emulators installed so I can't check if it is duplicated in there.  Since the full source is in the MyToolkit.VS2015 project, I'll try and trace through this weekend and see if I can get you more details.

**Comment by rsuter** [comment]
I have the latest emulator and it seems to work there... I will test it on a real device as soon as possible.

**Comment by rsuter** [comment]
Ok, it should be fixed in the latest commit... Please try again with the SampleUwpApp

**Comment by tomreich** [comment]
That did the trick.  Thanks for the quick & awesome support!

Any chance you can drop me a line next time you push a release out to Nuget?

**Comment by rsuter** [comment]
Ill inform you in this thread..

**Comment by rsuter** [comment]
MyToolkit v2.5.0 has been released on NuGet...

**Comment by tomreich** [comment]
Awesome, I can confirm this is now working in my app with MyToolkit pulled through NuGet.
