### ISSUE TITLE
HttpUtilityExtensions in two libraries

### ISSUE THREAD

**Issue by asd4059** [MyToolkit/MyToolkit#19]
Error CS0433 Type "HttpUtilityExtensions" exists in "MyToolkit.Extended, Version = 2.5.0.0, Culture = neutral, PublicKeyToken = null", and the "MyToolkit, Version = 2.5.0.0, Culture = neutral, PublicKeyToken = 3e349a1360994d26"

**Comment by rsuter** [comment]
Should be fixed in v2.5.2, please try again

**Comment by asd4059** [comment]
Yes it's OK.
