### ISSUE TITLE
Error building project with MyToolkit.Extended 2.5.0

### ISSUE THREAD

**Issue by asd4059** [MyToolkit/MyToolkit#20]
When I build the project (UWP build 10563):
Microsoft.Net.CoreRuntime.targets(237,5): error MSB3030:
failed to copy a file"C:\Users\asd40\.nuget\packages\MyToolkit.Extended\2.5.0\lib\uap10.0\MyToolkit.Extended\Libraries\DotNetZip\Changes.txt" - file not Found.
failed to copy a file"C:\Users\asd40\.nuget\packages\MyToolkit.Extended\2.5.0\lib\uap10.0\MyToolkit.Extended\Libraries\DotNetZip\License.zlib.txt" - file not Found.

**Comment by rsuter** [comment]
Should be fixed in v2.5.2, please try again

**Comment by asd4059** [comment]
Yes it's OK.
