### ISSUE TITLE
Hamburger search not working on Windows Phone 10

### ISSUE THREAD

**Issue by tomreich** [MyToolkit/MyToolkit#22]
There appears to be an issue with the search bar in the Hamburger Menu on Windows Phone 10.  The search bar appears when the search button or hamburger button are tapped, and you can enter a search string.  But tapping enter on the virtual keyboard or tapping the on-screen search button next to the search string textbox does not appear to do anything.  The Hamburger Menu stays expanded and no navigation occurs.  Registered events on the searchItem.QuerySubmitted event do not appear to fire.

Can confirm this behavior is occurring on the SampleUwpApp when deployed to Windows Phone 10 build 10581 deployed to a Lumia 920.  This behavior does not appear to happen on a desktop deployment of the app.

Unfortunately there are no messages in the VS console when the search option is tapped.  However, when the Hamburger Menu is first expanded, the following message does appear in the console.  Note that this may be unrelated to this issue, and this message also appears on a desktop deployment.

>Error: BindingExpression path error: 'Content' property not found on 'Windows.Foundation.IReference`1<String>'. BindingExpression: Path='Content' DataItem='Windows.Foundation.IReference`1<String>'; target element is 'Windows.UI.Xaml.Controls.ContentPresenter' (Name='null'); target property is 'Content' (type 'Object')

Let me know if you need more info and I will do my best to get it for you.

**Comment by rsuter** [comment]
It seems that SearchBox is not recommended for UWP apps: 
https://msdn.microsoft.com/library/windows/apps/windows.ui.xaml.controls.searchbox.aspx
I will try to use AutoSuggestBox instead...

**Comment by rsuter** [comment]
Fixed in commit
https://github.com/MyToolkit/MyToolkit/commit/5c8c284d6814497b7f27f63a7bf8571fedd9a722

**Comment by rsuter** [comment]
Now fixed in NuGet version 2.5.3

**Comment by tomreich** [comment]
Confirmed.  You rock.  Thanks again!
