### ISSUE TITLE
ScrollableHtmlView will support the html style 

### ISSUE THREAD

**Issue by startewho** [MyToolkit/MyToolkit#25]
Like these html code
```
<p style="font-size:16">P1</p>
<p style="font-size:18">P2</p>
```
will the control can support such style when translate the html to xaml?

**Comment by rsuter** [comment]
In v2.5.5 you can implement your own ParagraphGenerator: 

	public MyParagraphGenerator : ParagraphGenerator
	{
		protected override RichTextBlock CreateTextBlock(HtmlNode node, IHtmlView htmlView)
		{
			var textBlock = base.CreateTextBlock(node, htmlView);
			// TODO: Set your styles
			return textBlock; 
		}
	}
	
Then you just need to replace the existing generator: 

	HtmlView.Generators["p"] = new MyParagraphGenerator()

See https://github.com/MyToolkit/MyToolkit/wiki/HtmlView

**Comment by startewho** [comment]
Thanks so much.It's a great work
