### ISSUE TITLE
HtmlView Font Size Binding

### ISSUE THREAD

**Issue by hermitdave** [MyToolkit/MyToolkit#26]
Hi,

I am using HtmlView in the following manner
<DataTemplate x:Key="CalloutHtmlTemplate">
      <myToolkitExtended:HtmlView 
            Style="{StaticResource ArticleHtmlStyle}"
            FontSize="{Binding ElementName=articlePage, Path=DataContext.ArticleDetailBodyFontSize}"
            Margin="12.8"
            Html="{Binding Content}" />
 </DataTemplate>

While this work, modifying the ArticleDetailBodyFontSize does not have any effect on rendered html content. scrolling up or down forcing rendering uses the new / modified font size. how can one ensure that font sizes changes are reflected immediately ?

Hermit

**Comment by rsuter** [comment]
Just to verify if its a bug in HtmlView: Is the binding working if you use a ScrollableHtmlView instead of the HtmlView?

**Comment by hermitdave** [comment]
Rico,

My requirement was met by HtmlView and never tried scrollable html view as the html view is a part of list view template and the view lives within listview's scrollviewer. I could create a repro if you wish

Hermit

**Comment by rsuter** [comment]
Just want to see if the binding is working in ScrollableHtmlView as in this control, the view is regenerated if the FontSize property is changed.. (this change detection code is missing in HtmlView)

**Comment by hermitdave** [comment]
okay give me a few mins.. in process of building a release.. will testing it and post back

**Comment by hermitdave** [comment]
Hi,

ScrollableHtmlView doesn't reflect changes to fontsize changes either

Hermit

**Comment by rsuter** [comment]
I updated the sample apps (SampleUwpApp and SampleWindowsStoreApp) and binding FontSize there works... Can you reproduce the problem in these sample apps?

**Comment by hermitdave** [comment]
Let me take a look at sample apps tomorrow. In my beta app, I can reproduce it easily and has been raised by both internal tests and Microsoft

**Comment by rsuter** [comment]
Ok, please inform me after your checks.. What do you mean by "raised by both internal tests and Microsoft". Are you working for MS?

**Comment by hermitdave** [comment]
nah I work for a News company developing a first party app that is to be preinstalled on Windows 10 Mobile devices. The only obvious differences are
1) the HtmlView is within ListView - in one of the many data templates
2) the Fontsize increment / decrement is stored in settings and size is computed in ViewModel and PropertyChanged event is raised.
3) the FontSizei is bound to VM Property.

I will try to see rework my XAML to relay on another element rather than VM Property. Will let you know how things go

**Comment by rsuter** [comment]
Btw: You should not place a HtmlView inside a ScrollViewer because the whole content must be rendered... You should use the ScrollableHtmlView (with HeaderTemplate and FooterTemplate) which only renders the visible html (virtualizing) so that the initila rendering (eg page load) is much faster...

**Comment by hermitdave** [comment]
Let me try using ScrollableHtmlView in the app. Whatever keeps the memory usage under control - which sadly has been a concern for a while. Didn't have much luck binding to another element in the xaml.. will need to see what else I can do

**Comment by hermitdave** [comment]
Noticed an issue with ScrollableHtmlView.. 

ScrollViewer.VerticalScrollMode="Disabled"
ScrollViewer.IsVerticalScrollChainingEnabled="True"

don't seem to be doing anything..  the content within the ScrollableHtmlView still responds to pull independently of the parent. 

I will try and fork the repo in coming days and try to fix what I can. If I do, I will send you a PR. In the mean time I have used a simplistic solution using 
https://github.com/MacawNL/WinRT-RichTextBlock.Html2Xaml

**Comment by rsuter** [comment]
If you dont need scrolling, you should use HtmlView

**Comment by hermitdave** [comment]
I was only referring to your previous comment which said that I shouldn't place html view within scrollviewer as it is fully rendered :)

**Comment by rsuter** [comment]
If you need to show all html at once, use HtmlView, if you need scrolling use ScrollableHtmlView..

**Comment by rsuter** [comment]
... do not put a HtmlView inside a ScrollViewer

**Comment by rsuter** [comment]
... when using ScrollableHtmlView, you should not try to disable scrolling, but add your custom header and footer using the HeaderTemplate and FooterTemplate properties... otherwise it is the same as using HtmlView

**Comment by hermitdave** [comment]
thanks... in my usage html is one of the contents within the news article and all of the data including html is within listview.. I think my usage of htmlview was correct. Shame font size isn't reflecting. Will need to think of something

**Comment by rsuter** [comment]
In the sample app, binding FontSize works for me with HtmlView and ScrollableHtmlView

**Comment by rsuter** [comment]
But just in the latest source code, not with the latest NuGet release... the fix for HtmlView is not released yet.
