### ISSUE TITLE
Nuget package does not include the Youtube.GetVideoTitleAsync

### ISSUE THREAD

**Issue by hesa2020** [MyToolkit/MyToolkit#27]
Hello its me again :).
I noticed the Nuget package does not include the Youtube.GetVideoTitleAsync
I was wondering if it was intended or a "bug".
In order to get this function i have to manually download and compile the code and include the dll in my project, would just be easier for me to use nuget manager to update the dll.

**Comment by rsuter** [comment]
Oh no...  Are you sure? If it's missing, it's a bug

**Comment by rsuter** [comment]
I just downloaded the NuGet package and found the method in the WP7/W8 DLL: 

![image](https://cloud.githubusercontent.com/assets/2603405/11392000/11d54a70-9357-11e5-9efe-fcbccdec91cf.png)

**Comment by rsuter** [comment]
On what platform are you using the lib?

**Comment by rsuter** [comment]
Should be available in v2.5.8... Please reopen if you still have the issue.

**Comment by hesa2020** [comment]
Hello sorry for my late reply, i just:
1. Removed MyToolkit & MyToolkit.Extended references
2. Downloaded the MyToolkit.Extended v2.5.8.0 using Nuget package manager
3. Tried to compile

And i got the same thing again.

I am running on Windows 8.1 Pro, i am using Visual Studio 2013 my project use the .net version 4.5.3
Here is what i get:
![errorgetvideotitleasync](https://cloud.githubusercontent.com/assets/2501581/11969887/3c4f13e6-a8ef-11e5-942b-a4861bf271c4.png)
