### ISSUE TITLE
DataGrid headers shift more to the right then column data

### ISSUE THREAD

**Issue by Depechie** [MyToolkit/MyToolkit#28]
I've added following datagrid to my UWP app:
```
<myToolkitControls:DataGrid ItemsSource="{x:Bind Vm.Locations, Mode=OneWay}"
                        SelectionMode="Single"
                        SelectedItem="{x:Bind Vm.SelectedLocation, Mode=TwoWay, Converter={StaticResource XBindItemCastingConverter}}">
    <myToolkitControls:DataGrid.Columns>
        <myToolkitControls:DataGridTextColumn Header="Straat"
                                            Binding="{Binding StreetFormatted}"
                                            Width="2*" />
        <myToolkitControls:DataGridTextColumn Header="Stad / gemeente"
                                            Binding="{Binding CityFormatted}"
                                            Width="2*" />
        <myToolkitControls:DataGridTextColumn Header="Afstand"
                                            Binding="{Binding Distance}"
                                            Width="*" />
    </myToolkitControls:DataGrid.Columns>
</myToolkitControls:DataGrid>
```
So Widths are based on * but if you look at the screenshot below, you'll notice that the header values from column 2 and 3 are each shifted several pixels to the right in reference to the data inside the columns itself.
Any idea why?

![grid](https://cloud.githubusercontent.com/assets/351693/11430463/4a12a67c-9487-11e5-9c3c-8eff00c189d9.png)

**Comment by rsuter** [comment]
Should be fixed in v2.5.8. Please verify and report back...

**Comment by rsuter** [comment]
BTW: You could use a CellTemplate like this to draw lines between the cells: 

	<DataTemplate>
		<Border BorderThickness="1" BorderBrush="Red">
			<ContentPresenter Margin="15" Content="{Binding Control}" />
		</Border>
	</DataTemplate>

**Comment by Depechie** [comment]
Thanks for the quick fix on the headers! ( going to test the lines but that is not a prio ;) )
