### ISSUE TITLE
How to change the alternate row coloring

### ISSUE THREAD

**Issue by sandeepkavade** [MyToolkit/MyToolkit#29]
Hi,

I am a newbie to xaml and creating a windows universal application. For displaying the data from database I am Using DataGrid. I my application I have black background and font color is white. 

In datagrid I don't know how to change the background color of alternate row as it shows white text on somewhat whitish background color which is very hard to read. 

How should I change the alternate row color or disable it all together.

**Comment by rsuter** [comment]
You can set the 

    RowBackgroundEvenBrush="Transparent"
    RowBackgroundOddBrush="Transparent"

properties to remove the row backgrounds or change them...
You could also change the text color with the `Foreground` property: 

    <controls:DataGridTextColumn Foreground="Red" />

**Comment by rsuter** [comment]
Is your question answered?

**Comment by sandeepkavade** [comment]
Thanks, this is exactly what I wanted.
