### ISSUE TITLE
Isn't cleared backstack

### ISSUE THREAD

**Issue by asd4059** [MyToolkit/MyToolkit#30]
UWP project. MyToolkit 2.5.8.
_hamburgerFrameBuilder.Frame.ClearBackStack() - It does not clear BackStack.

**Comment by rsuter** [comment]
Just added a button to clear the back stack in the sample application SampleUwpApp. It worked for me... What exactly are you doing? Can you show us some code?

**Comment by asd4059** [comment]
## Way 1

### From ViewModelPage1 : ViewModelPageBase
```C#
Navigate(typeof(UI.Page2));
HamburgerManager.GetFrame().ClearBackStack();
```
**This code cleared backstack. Now it doesnt. Earlier this clears backstack.**

## Way2

### From ViewModelPage2 : ViewModelPageBase
```C#
protected override void OnLoaded()
        {
            if (Page.Frame.CanGoBack) // => false
                Page.Frame.ClearBackStack();
            base.OnLoaded();
        }
```
**Also not working. CanGoBack return false when it is called in OnLoaded**

## Way3

### From ViewModelPage2 : ViewModelPageBase
```C#
public CommandBase ClearCommand { get; }

public MainPageViewModel(MtPage page) : base(page)
        {
            ClearCommand = new RelayCommand(Clear);
        }

private void Clear()
        {
            if (Page.Frame.CanGoBack)
                Page.Frame.ClearBackStack();
        }
```
**This is manual launch. It works, but I'd like to use 1st or 2nd way.**

**Comment by asd4059** [comment]
I apologize, the problem is solved. The first way is working.

**Comment by rsuter** [comment]
Ok :-) thx for using the library...

**Comment by rsuter** [comment]
PS: Maybe you have to wait until the navigation has completed: 

    await frame.NavigateAsync(...);
    frame.ClearBackStack();
