### ISSUE TITLE
WPF - Change FontSize Header DataGrid

### ISSUE THREAD

**Issue by Bukoow** [MyToolkit/MyToolkit#31]
Hello !

I'm developing an universal application Windows 8.1 and I use your DataGrid Control in order to expose data.

But when I create a style, for example : 

    <Style TargetType="controls:DataGrid" x:Key="DataGridStyle">
        <Setter Property="HeaderBackground"  Value="{StaticResource BackgroundPageBrush}"/>
        <Setter Property="FontFamily" Value="{StaticResource GothamBook}"/>
         <Setter Property="FontSize" Value="8"/>
    </Style> 

The fontSize doesn't change ! I set the value to 8 or 48, and there is no change.

Can you help me please ? 

Thanks :)

**Comment by Bukoow** [comment]
And I've just thinking about that, how is it possible to change the color of a row when it is selected ?

**Comment by Bukoow** [comment]
I've some questions (yeah, sorry for my bad English ;) ) 
 - Is it possible to wrap element, if the text is too long ?
 - For the row, is it possible to change the view clicking on it ?

I know, there is a lot of questions but you're great ;)

**Comment by rsuter** [comment]
For the click event, you can register the Navigate event..

**Comment by rsuter** [comment]
Fixed in v2.5.9
