### ISSUE TITLE
Unable to view in object browser.

### ISSUE THREAD

**Issue by sandeepkavade** [MyToolkit/MyToolkit#34]
Hi, 

Just updated MyTookit to 2.5.8 and when I double click the MyToolkit or MyToolkit.Extended in References its saying "This project cannot be viewed in the object browser because it is unavailable or not yet built. Please ensure that the project is available and built.'

I don't know whether its a problem with 2.5.8 or any missing setting on my end. 

I am using it in a Windows Universal Application with Target version: Windows 10 (10.0;Build 10240) and Min version: Windows 10(10.0 Build 10240)

**Comment by rsuter** [comment]
Did you try to search the lib in the object browser and open it therer?

**Comment by sandeepkavade** [comment]
Yes, I am able to search and browse it from object browser. But just curious to know why its giving error when I double click from references?

**Comment by rsuter** [comment]
I had this problem with other DLLs too. I think this is a Visual Studio bug...
