### ISSUE TITLE
How to override LinkGenerator?

### ISSUE THREAD

**Issue by maxindahouze** [MyToolkit/MyToolkit#39]
It is necessary to change the Click Handler to my own version

**Comment by rsuter** [comment]
Just implement your own: 

    public class MyLinkGenerator : LinkGenerator 
    {
        ...
    }

And then assign it: 

    view.Generators["a"] = new MyLinkGenerator();

also see: https://github.com/MyToolkit/MyToolkit/wiki/HtmlView
