### ISSUE TITLE
LongListSelector not working as intended.

### ISSUE THREAD

**Issue by Rakim09** [MyToolkit/MyToolkit#4]
LongListSelector grouping items but jumping between them isn't working. Also if list is long scrolling doesn't work either. Am I missing something?

**Comment by rsuter** [comment]
On which platform are you using the control?

**Comment by Rakim09** [comment]
Windows Phone 8.1

**Comment by rsuter** [comment]
Have you checked out the sample application in the MyToolkit repository? Can you reproduce the problem there?

**Comment by Rakim09** [comment]
In sample application everything works fine. In my app I have 2 grid rows when I delete the first one it started working.

**Comment by rsuter** [comment]
So, it is now working for you and the issue can be closed?
