### ISSUE TITLE
Changing LinkGenerator.Foreground on the Loaded event of HtmlView has no effect when Html content is bound

### ISSUE THREAD

**Issue by r2d2rigo** [MyToolkit/MyToolkit#40]
Just followed the wiki's instructions for setting a custom foreground colour for one of the `HtmlView`'s generators, in this case `LinkGenerator`. It is advised to do that on the `Loaded` event of the `HtmlView`, however this is fired after the child controls have already been generated if the `Html` field is bound in XAML.

Setting both the `LinkGenerator.Foreground` and `HtmlView.Html` in the `Loaded` event works fine, though. This issue may affect other `IControlGenerator`s but I haven't checked it.

**Comment by rsuter** [comment]
I have to check why the generators can only be changed after the control has been loaded...

https://github.com/MyToolkit/MyToolkit/wiki/HtmlView

**Comment by r2d2rigo** [comment]
Maybe adding default `ThemeResources` for each `LinkGenerator` type/property that can be easily overwritten by apps that use the library? This would allow to style all `HtmlViews` at the same time.

**Comment by rsuter** [comment]
I just checked the source code, you should change the generators in the view's constructor. If you change/add the generators after the HTML is set, just call `Refresh()` (available in v2.5.9)
