### ISSUE TITLE
ScrollableHtmlView causing exception with HeaderTemplate and FooterTemplate

### ISSUE THREAD

**Issue by ovinix** [MyToolkit/MyToolkit#41]
I have Universal App project:

MainPage.xaml.cs
```
Frame.Navigate(typeof(PostPage),(Post)Item);
```

PostPage.xaml.cs
```
private void hwPostContent_Loaded(object sender, RoutedEventArgs e)
{
      hwPostContent.FontSize = PostFontSize;
      hwPostContent.Html = PostHTML;
 }
 private void HardwareButtons_BackPressed(object sender, BackPressedEventArgs e)
{
     e.Handled = true;
     Frame.GoBack();
 }
private void SettingsButton_Click(object sender, RoutedEventArgs e)
{
      Frame.Navigate(typeof(SettingsPage));
}
```

PostPage.xaml
```
<mytoolkit:ScrollableHtmlView x:Name="hwPostContent" ShowHeader="True" Html="..." Loaded="hwPostContent_Loaded">
                <mytoolkit:ScrollableHtmlView.HeaderTemplate>
                    <DataTemplate>
                            <TextBlock Text="Smth"/>
                    </DataTemplate>
                </mytoolkit:ScrollableHtmlView.HeaderTemplate>
</mytoolkit:ScrollableHtmlView>
```

SettingsPage.xaml.cs
```
private void HardwareButtons_BackPressed(object sender, BackPressedEventArgs e)
{
      e.Handled = true;
      Frame.GoBack();
}
```

There is no problem:
1. MainPage -> PostPage
2. Press 'Back' (going back to MainPage)
3. MainPage -> PostPage

There is a problem:
1. MainPage -> PostPage
2. PostPage -> SettingsPage
3. Press 'Back' (going back to PostPage)
4. Crash..

Error message:
```
System.ArgumentException: Value does not fall within the expected range.
   at Windows.UI.Xaml.Controls.ContentPresenter.put_Content(Object value)
   at MyToolkit.Controls.ScrollableHtmlView.UpdateHeader()
   at MyToolkit.Controls.ScrollableHtmlView.OnApplyTemplate()
   at Windows.UI.Xaml.Controls.ContentPresenter.put_Content(Object value)
   at MyToolkit.Controls.ScrollableHtmlView.UpdateHeader()
   at MyToolkit.Controls.ScrollableHtmlView.OnApplyTemplate()
```
FooterTemplate is causing the same error. There are no errors in both cases if PostPage.xaml looks like this:
```
<mytoolkit:ScrollableHtmlView x:Name="hwPostContent" ShowHeader="True" Html="..." Loaded="hwPostContent_Loaded"></mytoolkit:ScrollableHtmlView>
```

Any ideas?

**Comment by rsuter** [comment]
Is it possible that `PostHTML` is null when navigating back?

**Comment by rsuter** [comment]
I just tried to reproduce your problem, but this works for me... Can you upload a sample project where this exception occurs?

**Comment by ovinix** [comment]
No, as I understand, PostPage is cashed then going to SettingsPage, so after ```Frame.GoBack()``` all PostPage variables are the same as before.

Crash happening even before  ```hwPostContent_Loaded``` called, where I'm setting ```Html```.

You can see my project here - https://github.com/ovinix/PlayUA.mini/tree/temporary/PlayUA.mini

**Comment by ovinix** [comment]
So, I checked in debug and everything is good with my html variable in both cases. As I said, there is no problem after removing HeaderTemplate.

**Comment by rsuter** [comment]
Ok, the problem is that you set the page itself as DataContext (and not a POCO view model)... I have to check how to solve this...

**Comment by rsuter** [comment]
https://github.com/MyToolkit/MyToolkit/commit/00e191e1a091867ed6aeea584dfc4160618826fb

**Comment by ovinix** [comment]
Thank you! When should I see this update on Nuget?

**Comment by rsuter** [comment]
https://github.com/MyToolkit/MyToolkit/commit/f387285a74d2ba06ead27b04eb6da70dfbdfebc5

**Comment by rsuter** [comment]
Now: https://github.com/MyToolkit/MyToolkit/commit/0123595897e667d2c8711b8d0d060f7f2418fc94

**Comment by ovinix** [comment]
To be honest, I'm having one more scrolling issue with ScrollableHtmlView then setting a big amount of HTML. It's connected with usability. So then slowly scrolling up a huge HTML page in ScrollableHtmlView from the page bottom, it's randomly jumping to the top of the page, like there is nothing in between. If you have time and possibility to check this on the real device, a can show you post in my app which is causing this issue!
