### ISSUE TITLE
MtPivot does not work when no items are defined in the XAML

### ISSUE THREAD

**Issue by highfield** [MyToolkit/MyToolkit#50]
I need to declare the MtPivot without items at XAML level, because the actual content will be added at runtime. The problem is that the MtPivot throws an exception when there's no content (both in the XAML editor and once the code is running).

My workaround is pretty simple: Adding a dummy item in the XAML. Then, the runtime adds the desired MtPivotItems (two in my case), and finally removes the first one (the dummy).
That's not so bad, however I must trigger the item selection in some way, because the "SelectedIndex" is already zero, but the visual result is a mixture of both the items added. That is, once I click on any of the headers everything goes all right.

Well, simply I'd patch the possibility to remove all the items (will result an empty Pivot), and in that context the SelectedIndex should be set to -1.

I tested it only for UWP: I believe it should be pretty easy to reproduce.

**Comment by rsuter** [comment]
Fixed in https://github.com/MyToolkit/MyToolkit/commit/66491e2301f786001c88b3bb2506f1824105a650
