### ISSUE TITLE
Binding DataGridTextColumn Forground with converter will not pick up correct color

### ISSUE THREAD

**Issue by Depechie** [MyToolkit/MyToolkit#52]
#38 Was originally posted and said to be fixed.

Indeed now we can run the grid with forground binding, but it's still not picking up the correct color.
Cfr the example in #38 when the bool is True the foreground should be red, but we are not getting any red items in the grid.
Even though the value converter is returning color red.

**Comment by Depechie** [comment]
Any changes on this?

**Comment by rsuter** [comment]
The color must be a brush, just use: 

    public class BoolToColorConverter : IValueConverter
    {
        public object Convert(object value, Type targetType, object parameter, string language)
        {
            if (value != null && value is bool && (bool) value)
                return new SolidColorBrush(Colors.Red);

            return new SolidColorBrush(Colors.Black);
        }

        public object ConvertBack(object value, Type targetType, object parameter, string language)
        {
            throw new NotImplementedException();
        }
    }

**Comment by rsuter** [comment]
![image](https://cloud.githubusercontent.com/assets/2603405/18201876/0427d188-710d-11e6-9728-6eef5f894e59.png)

**Comment by rsuter** [comment]
Btw: Just check the VS Output window and you'll see the problem: 

```
Error: Converter failed to convert value of type 'Windows.UI.Color' to type 'Brush'; BindingExpression: Path='IsPrio' DataItem='TestMyToolkitGrid.Models.Location'; target element is 'Windows.UI.Xaml.Controls.TextBlock' (Name='null'); target property is 'Foreground' (type 'Brush'). 
Error: Converter failed to convert value of type 'Windows.UI.Color' to type 'Brush'; BindingExpression: Path='IsPrio' DataItem='TestMyToolkitGrid.Models.Location'; target element is 'Windows.UI.Xaml.Controls.TextBlock' (Name='null'); target property is 'Foreground' (type 'Brush'). 
Error: Converter failed to convert value of type 'Windows.UI.Color' to type 'Brush'; BindingExpression: Path='IsPrio' DataItem='TestMyToolkitGrid.Models.Location'; target element is 'Windows.UI.Xaml.Controls.TextBlock' (Name='null'); target property is 'Foreground' (type 'Brush'). 
```

**Comment by Depechie** [comment]
Awesome, will try that! Hmm missed that VS output :/

**Comment by Depechie** [comment]
Works like a charm
