### ISSUE TITLE
How to use the order of the records in a DataGrid in a backend data source

### ISSUE THREAD

**Issue by Astone** [MyToolkit/MyToolkit#54]
I'm using the DataGrid with many records (> 100k), so I implemented some sort of backend filtering and pagination. To get the correct ordering from my data source (a JSON-RPC-API) I need to know which OrderIndex (i.e. which column) has been selected and in which direction the records should be sorted. I also need to reload my data whenever someone clicks on a column header. I couldn't find an EventHandler to do this.

Is this possible in the current DataGrid implementation? How can I do this in my code? Should I implement this in my ViewModel? Or where could I implement this in MyToolkit.DataGrid?

**Comment by rsuter** [comment]
You should check the property `SelectedColumn` for this...

**Comment by rsuter** [comment]
With the `DependencyPropertyChangedEvent` class you can listen for dependency property changes (ie the SelectedColumn property)

**Comment by rsuter** [comment]
.. and please tell me more about the performance of the DataGrid with 100k items :-)

**Comment by rsuter** [comment]
Hmm, `SelectedColumn` is not a dependency property, so `DependencyPropertyChangedEvent` will not work here... Do you need a change event?

**Comment by Astone** [comment]
Well I use backend pagination, so I select only a subset of ca. 30 items from my database storing the 100k records, that makes it fast enough :)

And yeah, unfortunately I do need an event, because changing the order changes the items in the subset. For now I can just disable ordering on each column and then I'll just wait and see if my users start complaining or not :p

**Comment by Astone** [comment]
Here is a simplified example of what I'm trying to do. Let's say I have seven items in my database:
[ 1 2 3 4 5 6 7 ]

I can show only 3 items per page and I'm displaying the second page:
[ 1 2 3 ] **[ 4 5 6 ]** [ 7 ]

Now let's reorder them. 5 is my center item on the page, so I want to show the page containing number 5, which is the first page:
**[ 7 6 5 ]** [ 4 3 2 ] [ 1 ]

**Comment by rsuter** [comment]
Adding a `SelectedColumnChanged` event should be simple

**Comment by Astone** [comment]
Ok cool, I'll do that. Thanks.

**Comment by rsuter** [comment]
Nuget 2.5.12

**Comment by rsuter** [comment]
Reference: https://github.com/MyToolkit/MyToolkit/pull/57
