### ISSUE TITLE
How to make DataGrid cells editable

### ISSUE THREAD

**Issue by Astone** [MyToolkit/MyToolkit#55]
According to the wiki, DataGrids can contain:

 * Custom cell types to support other object types and writeable cells.

But how? I can't get it to work and I don't see an example of DataGrid with editable cells.

**Comment by Astone** [comment]
I forgot to mention that I need only the cells in _some_ columns to be editable, not all of them. So I need a different CellTemplate per Column.

**Comment by rsuter** [comment]
You can use the `DataGridTemplatedColumn` column to specify a cell template per column: 

https://github.com/MyToolkit/MyToolkit/blob/master/src/MyToolkit.Extended/Controls/DataGrid/DataGridTemplatedColumn.cs

**Comment by Astone** [comment]
Thanks Rico!
Sorry, I missed that :S
