### ISSUE TITLE
Onscroll data loading in datagrid of mytoolkit in uwp

### ISSUE THREAD

**Issue by govindrawat55** [MyToolkit/MyToolkit#63]
I want to do virtualization in my toolkit grid.
I want to show only 10 records first time then after scroll it load next 10 records.

**Comment by govindrawat55** [comment]
<ScrollViewer x:Name="sv"  Margin="20,280,20,0" HorizontalScrollBarVisibility="Auto" RelativePanel.AlignRightWithPanel="True" RelativePanel.AlignLeftWithPanel="True" ViewChanged="ScrollViewer_ViewChanged">
            <Toolkit:DataGrid x:Name="DoGrid" Grid.Row="1" 
                           ItemsSource="{Binding Product}" 
                           SelectionMode="Single"
                           SelectedItem="{Binding SelectedPerson, Mode=TwoWay}"
                           DefaultOrderIndex="1" 
                           Height="Auto"
                           HeaderBackground="#FF094AB2" Foreground="White" RowBackgroundEvenBrush="#FFB3C6E7" RowBackgroundOddBrush="#FFD9E2F3" FontSize="14"
                           RelativePanel.AlignLeftWithPanel="True" RelativePanel.AlignRightWithPanel="True" Margin="0">
                <Toolkit:DataGrid.Columns>
                    <Toolkit:DataGridTemplatedColumn Width="100"  CanSort="False">
                        <Toolkit:DataGridTemplatedColumn.Header>
                            <CheckBox x:Name="OptionsAllCheckBox" IsThreeState="True"  Checked="SelectAll_Checked" Unchecked="SelectAll_Unchecked" Indeterminate="SelectAll_Indeterminate"/>
                        </Toolkit:DataGridTemplatedColumn.Header>
                        <Toolkit:DataGridTemplatedColumn.CellTemplate>
                            <DataTemplate>
                                <CheckBox IsChecked="{Binding Checked, Mode=TwoWay}" Checked="Option_Checked" Unchecked="Option_Unchecked" />
                            </DataTemplate>
                        </Toolkit:DataGridTemplatedColumn.CellTemplate>
                    </Toolkit:DataGridTemplatedColumn>
                    <Toolkit:DataGridTextColumn Width="200" Header="number" Binding="{Binding Number}" />
                    <Toolkit:DataGridTextColumn Width="300" Header="Description" Binding="{Binding Description}" />
                </Toolkit:DataGrid.Columns>
            </Toolkit:DataGrid>
        </ScrollViewer>

**Comment by patilketan888** [comment]
would you please share your code behind for select all check box.
