### ISSUE TITLE
How to use the DataGrid without the HamburgerFrame?

### ISSUE THREAD

**Issue by Goldstrike** [MyToolkit/MyToolkit#69]
I have studied the UWP sample for the **DataGrid**, but I can't adapt it to my case...
I have to use a "**paging:MtPage**" to implement the DataGrid, but this raises an error at the launch of my app: I get a System.NullReferenceException in "`rootFrame.Navigate(typeof(HomePage), e.Arguments);`" where **HomePage** is the page that contains the DataGrid.
- Isn't it possible to implement the DataGrid without the "paging:MtPage"?
- Also, should I use the Toolkit's ViewModelBase? I would rather use MVVMLight...

**Comment by rsuter** [comment]
Of course, you can also use only the DataGrid control in your XAML with your preferred MVVM framework. Check the Windows 8 sample app...

**Comment by Goldstrike** [comment]
Thanks for your return!
Y've looked at the Windows 8 sample, but you're still using "**page:MtPage**" on each page, and your paging implementation, as you've detailed [here](https://github.com/MyToolkit/MyToolkit/wiki/Paging-Overview)

But so is it possible to use the DataGrid without implementing this paging?
As you use override methods (**OnSaveState()**, **OnLoadState()**) in the code-behind of the DataGridPage, I haven't manage to do this.

**Comment by rsuter** [comment]
Yes, of course you can use just the DataGrid control with the default UWP Page implementation... The MyToolkit MtPage is just used for better cache management, etc. but it is a distinct feature...

**Comment by Goldstrike** [comment]
So I will try again :-)
Another question, is there a way to "filter" each column easily? I would like to reproduce the Excel comportment, that allows to select a specific value for a column...

**Comment by rsuter** [comment]
You can bind to an ObservableView and add and remove filters there => see UWP sample... otherwise there are no built-in filter capabilities

**Comment by rsuter** [comment]
Did you find a solution to this?

**Comment by Goldstrike** [comment]
Sorry for the response time, but I don't work on this projet at full time.
The customer finally agreed to have a unique filter for all columns.
But I don't yet know if I will keep the MtPage implementation, as I currently meet another problem: I will open a new issue to describe this.

**Comment by Goldstrike** [comment]
I finally posted my request in an existing topic:
[https://github.com/MyToolkit/MyToolkit/issues/51](https://github.com/MyToolkit/MyToolkit/issues/51)

**Comment by rsuter** [comment]
Can we close this issue?

**Comment by Goldstrike** [comment]
Yes
