### ISSUE TITLE
Links (a) display in one row (wrapping not working)

### ISSUE THREAD

**Issue by MarekLani** [MyToolkit/MyToolkit#7]

**Comment by rsuter** [comment]
Will be fixed in the newest NuGet package. Please download the current sources and try the current implementation in one of the sample applications (SampleUwpApp or SampleWindowsStoreApp).

**Comment by rsuter** [comment]
PS: HtmlTextBlock/FixedHtmlTextBlock have been renamed to ScrollableHtmlView/HtmlView.

**Comment by MarekLani** [comment]
Tried it and it works. Thanks a lot! :)

**Comment by rsuter** [comment]
NuGet package will be released as soon as the final Windows 10 SDK is available...
