### ISSUE TITLE
How fill Hamburger dynamic?

### ISSUE THREAD

**Issue by DerKnerd** [MyToolkit/MyToolkit#70]
Hi,

I have a program, where I fill the hamburger on the side dynamic. The page is for something like 10 links the same, just the parameter changes. Now I cannot navigate from Page1 with parameter 1 to Page1 with parameter 2...

Is there a way how to achieve that?

Greetings
Knerd

**Comment by rsuter** [comment]
Setting UseSinglePageInstance to false is not an option?

**Comment by DerKnerd** [comment]
Works nearly like a charm, just the hamburger doesn't highlight the right button do you have a solution for that?

**Comment by rsuter** [comment]
In the next version you can override the IsHamburgerItemForPage method in HamburgerFrameBuilder (just create a class inheriting HamburgerFrameBuilder) and provide your own logic to navigate to an existing page or control which hamburger item is selected... Can you clone the source code and check if it is working for you?

Commit: https://github.com/MyToolkit/MyToolkit/commit/a901cdae26aac5e2d945ec047fb961efa9ffc7f0

**Comment by rsuter** [comment]
Available in v2.5.12
