### ISSUE TITLE
Refresh data of the DataGrid

### ISSUE THREAD

**Issue by Goldstrike** [MyToolkit/MyToolkit#72]
Hello,

I've followed the steps described here [https://github.com/MyToolkit/MyToolkit/wiki/ViewModelBase](ViewModelBase), but I can't refresh the data of the DataGrid, whereas the first load works well.

My ViewModel looks like this:
`
    public class HomeViewModel : ViewModelBase
    {
    	...
    	private SQLiteDataService sqliteDataService;
    	
    	private ObservableCollection<Car_Form> _carForms;
    	public ObservableCollection<Car_Form> CarForms
    	{
    		get { return _carForms; }
    		set { Set(ref _carForms, value); }
    	}
    	
    	public HomeViewModel()
    	{
    		this.sqliteDataService = new SQLiteDataService();
    		...
    	}
    	
    	public void LoadCar_Forms()
    	{
    		List<Car_Form> carForms = sqliteDataService.GetCar_Form();
    		_carForms = new ObservableCollection<Car_Form>(carForms);
    	}		
    	 
    	public void RefreshCar_Forms()
    	{
    		Car_Form newCarForm = new Car_Form{ ... };
    		sqliteDataService.InsertCar_Form(newCarForm);
    		LoadCar_Forms();
    	}
    }	
`

And my XAML looks like this:
`    <controls:DataGrid x:Name="DataGrid" Grid.Row="1"
    				   ItemsSource="{Binding CarForms}"
    				   SelectionMode="Single"
    				   DefaultOrderIndex="1">
    	<controls:DataGrid.Columns>
    		<controls:DataGridTextColumn Width="*" Header="Form Nr" Binding="{Binding form_id}" />
    		<controls:DataGridTextColumn Width="*" Header="Submitter" Binding="{Binding submitter}" />
    		<controls:DataGridTextColumn Width="*" Header="Company" Binding="{Binding company}" />
    		...
    	</controls:DataGrid.Columns>
    </controls:DataGrid>`

And the Model looks like this:
`    public class Car_Form
    {
    	[PrimaryKey, NotNull]
    	public int form_id { get; set; }
    	[MaxLength(100), NotNull]
    	public string form_code { get; set; }
    	[MaxLength(200), NotNull]
    	public string submitter { get; set; }
    	...
    }`

When I enter the first time in **LoadCar_Forms()** the data are well displayed: there is no problem with SQLite.
When I try to refresh the data, I enter in **RefreshCar_Forms()** and I call again LoadCar_Forms(), but the new data are not displayed in the DataGrid.
But if I close and relaunch the app, the new data is this time correctly loaded and displayed!

Where is my mistake?

**Comment by rsuter** [comment]
In LoadCar_Forms you need to assign the property instead of the field: 

CarForms =

**Comment by Goldstrike** [comment]
Oh right thank you...
`
