### ISSUE TITLE
Hamburger menu and BottomAppBar: how to manage?

### ISSUE THREAD

**Issue by Goldstrike** [MyToolkit/MyToolkit#73]
Hello, 
I use the MyToolkit's hamburger, but I would like to display an BottomAppBar on some pages: the bar is positioned over the burger menu and I can't seen the bottom hamburger item.

The BottomAppBar is declared like this in my XAML:
`    <paging:MtPage.BottomAppBar>
        <CommandBar>
            <AppBarButton Icon="Refresh" Label="Refresh" Click="OnRefresh_Click" />
            <AppBarButton Icon="Add" Label="Add" Click="OnAdd_Click" />
            <AppBarButton Icon="Delete" Label="Delete" Click="OnDelete_Click" />
        </CommandBar>
    </paging:MtPage.BottomAppBar>`

Is there a way to solve this case?

**Comment by rsuter** [comment]
Can you attach a sample project?

**Comment by Goldstrike** [comment]
I've reproduced this in the UWP MyToolkit sample:
[http://img15.hostingpics.net/pics/802263HamburgerAppBarBottom.png](screenshot)

I've uploaded the XAML file here:
[http://s000.tinyupload.com/index.php?file_id=53362154118353943156](link)

**Comment by Goldstrike** [comment]
Does someone have an idea?
Do I need to attach the full sample project?

**Comment by rsuter** [comment]
I think its fine. I didnt have the time to look into it

**Comment by rsuter** [comment]
A quick workaround would be to set a margin: 

        <CommandBar Margin="48,0,0,0">

Should the Hamburger automatically set this margin on pages?

**Comment by rsuter** [comment]
Added AppBar margin handling to Hamburger: https://github.com/MyToolkit/MyToolkit/commit/ebbe65ad07edd6e0a05b78c559087a84f9fa2526
