### ISSUE TITLE
YouTube: HttpRequestException ("HttpVersion Http20") in UWP

### ISSUE THREAD

**Issue by 9kon** [MyToolkit/MyToolkit#8]
Hello I like your toolkit and was planing on using it in a Windows 1o UWP app, to get some YouTube files from links.

I tried it in a windows 8 app and it works no problem but when i try it on windows 10 I get the following error.

'youtubetest.exe' (CoreCLR: CoreCLR_UAP_Domain): Loaded 'c:\users\kasper\documents\visual studio 2015\Projects\youtubetest\youtubetest\bin\x86\Debug\AppX\System.Text.RegularExpressions.dll'. Cannot find or open the PDB file.
'youtubetest.exe' (CoreCLR: CoreCLR_UAP_Domain): Loaded 'c:\users\kasper\documents\visual studio 2015\Projects\youtubetest\youtubetest\bin\x86\Debug\AppX\System.Net.Http.dll'. Cannot find or open the PDB file.
'youtubetest.exe' (CoreCLR: CoreCLR_UAP_Domain): Loaded 'c:\users\kasper\documents\visual studio 2015\Projects\youtubetest\youtubetest\bin\x86\Debug\AppX\System.Net.Primitives.dll'. Cannot find or open the PDB file.
'youtubetest.exe' (CoreCLR: CoreCLR_UAP_Domain): Loaded 'c:\users\kasper\documents\visual studio 2015\Projects\youtubetest\youtubetest\bin\x86\Debug\AppX\System.Private.Networking.dll'. Cannot find or open the PDB file.
'youtubetest.exe' (CoreCLR: CoreCLR_UAP_Domain): Loaded 'c:\users\kasper\documents\visual studio 2015\Projects\youtubetest\youtubetest\bin\x86\Debug\AppX\System.Net.Requests.dll'. Cannot find or open the PDB file.
'youtubetest.exe' (CoreCLR: CoreCLR_UAP_Domain): Loaded 'c:\users\kasper\documents\visual studio 2015\Projects\youtubetest\youtubetest\bin\x86\Debug\AppX\System.Collections.NonGeneric.dll'. Cannot find or open the PDB file.
'youtubetest.exe' (CoreCLR: CoreCLR_UAP_Domain): Loaded 'c:\users\kasper\documents\visual studio 2015\Projects\youtubetest\youtubetest\bin\x86\Debug\AppX\Internal.Net.dll'. Cannot find or open the PDB file.
Exception thrown: 'System.Net.Http.HttpRequestException' in mscorlib.ni.dll

My test code looks like this.

private async void getyoutube()
        {
            try
            {
                var Url = await YouTube.GetVideoUriAsync("Z - TQ98mRAiw", YouTubeQuality.QualityLow);
                
            }
            catch (Exception ex)
            {
              
            }
        }

**Comment by rsuter** [comment]
I'm currently working on the UWP version and most things already work. However I'm waiting for the final SDK release before publishing the new version to NuGet. For now, download the source code and add the projects `src\MyToolkit\MyToolkit.csproj` and `src\MyToolkit.Extended.WinRT\MyToolkit.Extended.Uwp.csproj` to your solution and add them as project references to your project.

**Comment by 9kon** [comment]
Thank for the quick reply,, unfortuneatly i still get a Exception thrown: 'System.Net.Http.HttpRequestException' in mscorlib.ni.dll

if apears to happen here 

#if WINRT

        /// <exception cref="WebException">An error occurred while downloading the resource. </exception>
        private static async Task<string> HttpGetAsync(string uri)
        {
            using (var client = new HttpClient())
            {
                client.DefaultRequestHeaders.Add("User-Agent", BotUserAgent);
                var response = await client.GetAsync(uri);
                return await response.Content.ReadAsStringAsync();
            }
        }

#else

on the return await response.Content.ReadAsStringAsync();

**Comment by 9kon** [comment]
actually it on the var response = await client.GetAsync(uri);

**Comment by rsuter** [comment]
Yes, I have the same exception with the message "HttpVersion Http20": I think the HttpClient tries to use HTTP 2.0 but it is not implemented in UWP... I asked a MS dev whether this is a bug...

**Comment by 9kon** [comment]
okay nothing to do but wait then,, but thank you for the great work anyway.

**Comment by rsuter** [comment]
Yes, ill update this issue as soon as i have more info.

**Comment by rsuter** [comment]
It will be fixed soon

**Comment by ljw1004** [comment]
I'm on the VS/.NET/UWP team at Microsoft. Confirmed that this will be fixed in the final "VS2015 RTM tools for Windows 10". (which alas aren't available just quite yet...)

**Comment by Englbach** [comment]
So, everyone will wait for this problem.

**Comment by rsuter** [comment]
Please update to version 2.4.0 and report if its working now...
