### ISSUE TITLE
MyToolkit support on universal VS 2015 RC?

### ISSUE THREAD

**Issue by Englbach** [MyToolkit/MyToolkit#9]
Could not load file or assembly 'system.net, version=2.0.5.0' on VS2015 RC universal and system.net.http...  when run mytoolkit

**Comment by rsuter** [comment]
Are you using the NuGet package or the newest sources?

**Comment by Englbach** [comment]
Yes. I upgraded it .

**Comment by Englbach** [comment]
and "system.net.http.httprequestException" was thrown

**Comment by rsuter** [comment]
See https://github.com/MyToolkit/MyToolkit/issues/8
